import { StyleSheet } from "react-native";
import { RADIUS } from "@/theme/radii";

export const detailStyles = StyleSheet.create({
  detailModal: {
    borderRadius: RADIUS["2xl"],
    borderWidth: 0,
    width: "100%",
    maxWidth: 390,
    maxHeight: "90%",
    alignSelf: "center",
    overflow: "hidden",
  },
  detailScroll: { flexShrink: 1 },
  detailBody: { gap: 12, padding: 16 },
  detailHero: {
    borderRadius: RADIUS.xl,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  detailHeroIcon: {
    width: 48,
    height: 48,
    borderRadius: RADIUS["2xl"],
    alignItems: "center",
    justifyContent: "center",
  },
  detailHeroText: { flex: 1, minWidth: 0 },
  detailHeroLabel: {
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  detailHeroAmount: {
    marginTop: 4,
    fontSize: 28,
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },
  detailDescription: { borderRadius: RADIUS.lg, padding: 14, gap: 7 },
  detailSectionLabel: {
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  detailDescriptionText: { fontSize: 16, fontWeight: "500", lineHeight: 22 },
  detailMetaGrid: { flexDirection: "row", gap: 10 },
  detailMetaItem: {
    flex: 1,
    minWidth: 0,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  detailMetaText: { flex: 1, minWidth: 0 },
  detailMetaLabel: {
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  detailMetaValue: { marginTop: 3, fontSize: 13, fontWeight: "600" },
  detailActions: { flexDirection: "row", gap: 10 },
  detailActionBtn: {
    flex: 1,
    height: 48,
    borderRadius: RADIUS.lg,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  detailActionText: { fontSize: 14, fontWeight: "700" },
});
