import { StyleSheet } from "react-native";

export const recordModalStyles = StyleSheet.create({
  recordModal: {
    borderWidth: 0,
    borderRadius: 20,
    width: "100%",
    maxWidth: 390,
    maxHeight: "90%",
    alignSelf: "center",
    overflow: "hidden",
  },
  recordScroll: { flexShrink: 1, maxHeight: "100%" },
  recordBody: { padding: 16, paddingBottom: 20 },
  conceptoInput: {
    height: 42,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 4,
  },
  lineItemCard: {
    borderWidth: 1,
    borderRadius: 12,
    marginBottom: 10,
    overflow: "hidden",
  },
  lineItemAmountRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  lineItemPrefix: {
    fontSize: 15,
    fontWeight: "700",
  },
  lineItemAmountInput: {
    flex: 1,
    fontSize: 15,
    fontWeight: "600",
    fontVariant: ["tabular-nums"],
    padding: 0,
    textAlignVertical: "center",
  },
  removeLineItemBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  addTagInlineBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
  },
  addTagInlineText: {
    fontSize: 11,
    fontWeight: "600",
  },
  selectedTagInlineChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    maxWidth: 130,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
  },
  selectedTagLabel: {
    fontSize: 11,
    fontWeight: "700",
  },
  lineItemDivider: {
    height: 1,
    marginHorizontal: 10,
  },
  lineItemDescRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  lineItemDescIcon: {
    marginTop: 1,
  },
  lineItemDescInput: {
    flex: 1,
    minHeight: 26,
    fontSize: 13,
    fontWeight: "500",
    padding: 0,
  },
  addLineItemBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1.5,
    borderStyle: "dashed",
  },
  addLineItemText: {
    fontSize: 14,
    fontWeight: "600",
  },
  lineItemsTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 4,
    marginTop: 6,
    marginBottom: 8,
    borderTopWidth: 1,
  },
  lineItemsTotalLabel: {
    fontSize: 15,
    fontWeight: "700",
  },
  lineItemsTotalValue: {
    fontSize: 18,
    fontWeight: "700",
  },
  tagsOverlay: {
    position: "absolute",
    zIndex: 40,
    elevation: 40,
  },
  recordActions: { flexDirection: "row", gap: 10, marginTop: 4 },
  recordCancel: {
    flex: 1,
    height: 52,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  recordSubmit: {
    flex: 1,
    height: 52,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  recordCancelText: { fontSize: 15, fontWeight: "700" },
  recordSubmitText: { fontSize: 15, fontWeight: "700" },
});
