import { StyleSheet } from "react-native";

export const expensesStyles = StyleSheet.create({
  searchBanner: {
    borderRadius: 14,
    borderWidth: 0,
    padding: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 10,
  },
  searchBannerMobile: { marginHorizontal: 14 },
  selectionBar: {
    marginHorizontal: 14,
    marginBottom: 10,
    borderWidth: 0,
    borderRadius: 14,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  selectionText: { flex: 1, minWidth: 0, fontSize: 15, fontWeight: "600" },
  selectionActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  selectionBtn: {
    width: 42,
    height: 42,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionHeader: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 8 },
  dateGroupLabel: {
    paddingHorizontal: 4,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 0,
  },
  loadOlderBtn: {
    minHeight: 48,
    borderWidth: 0,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  loadOlderText: { fontSize: 12, fontWeight: "600", letterSpacing: 0 },
});
