import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  shell: { flex: 1, flexDirection: "row", padding: 12, gap: 12 },
  shellCompact: { flexDirection: "column", padding: 0, gap: 0 },
  content: { flex: 1 },
  pageScroll: { paddingBottom: 136 },
  pageScrollMobile: { paddingHorizontal: 14 },
  loginScreen: { flex: 1, alignItems: "center", justifyContent: "center", padding: 26 },
  loginMark: { width: 78, height: 78, borderRadius: 18, borderWidth: 0, alignItems: "center", justifyContent: "center", marginBottom: 18 },
  loginTitle: { fontSize: 28, fontWeight: "700", letterSpacing: 0, textAlign: "center" },
  googleLoginBtn: { minWidth: 232, minHeight: 50, marginTop: 22, borderRadius: 12, paddingVertical: 12, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10 },
  googleLoginText: { fontSize: 15, fontWeight: "700" },
  loginStatus: { marginTop: 14, fontSize: 12, fontWeight: "500", textAlign: "center" },
  topBar: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
  topBarMobile: { marginBottom: 0, paddingHorizontal: 12, paddingVertical: 10, position: "relative" },
  headerTitleFade: { position: "absolute", left: 4, top: -1 },
  headerLeft: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 10, zIndex: 1 },
  headerLogo: { width: 40, height: 40, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  titleBlock: { flex: 1, minWidth: 0 },
  pageTitle: { fontSize: 26, fontWeight: "700", letterSpacing: 0 },
  pageTitleMobile: { fontSize: 20 },
  pageSub: { fontSize: 13, fontWeight: "500" },
  pageSubMobile: { fontSize: 14 },
  headerReadableTextDark: { textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 8 },
  headerReadableTextLight: { textShadowOffset: { width: 0, height: 0.25 }, textShadowRadius: 0.7 },
  themeToggle: { width: 52, height: 30, borderRadius: 999, paddingHorizontal: 3, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  themeThumb: { width: 24, height: 24, borderRadius: 12, backgroundColor: "#ffffff" },
  periodControls: { paddingHorizontal: 14, paddingTop: 2, paddingBottom: 0, gap: 8 },
  periodActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  periodSelect: { minHeight: 42, borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  periodMonthSelect: { flex: 1, minWidth: 0 },
  periodSelectText: { fontSize: 14, fontWeight: "600" },
  periodToday: { width: 42, height: 42, borderRadius: 10, borderWidth: 0, alignItems: "center", justifyContent: "center" },
  selectButton: { borderRadius: 10, paddingHorizontal: 12, minHeight: 42, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8, borderWidth: 1 },
  selectButtonText: { flex: 1, minWidth: 0, fontWeight: "600" },
  selectModalOverlay: { flex: 1 },
  selectMenu: { position: "absolute", borderWidth: 1, borderRadius: 10, overflow: "hidden" },
  selectMenuList: { flexShrink: 1 },
  selectMenuContent: { paddingVertical: 4 },
  selectOptionRow: { minHeight: 36, borderRadius: 8, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", gap: 6 },
  selectOptionLabel: { flex: 1, minWidth: 0, fontSize: 13, fontWeight: "600" },
  loadingBar: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 10 },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 12 },
  statsGridMobile: { paddingHorizontal: 14, paddingTop: 4, paddingBottom: 10, gap: 8, marginBottom: 0 },
  statCard: { flexGrow: 1, flexBasis: "48%", minWidth: 0, borderWidth: 0, borderRadius: 14, padding: 12, position: "relative", flexDirection: "row", alignItems: "center", gap: 8 },
  statIcon: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" },
  statContent: { flex: 1, minWidth: 0 },
  statLabel: { fontSize: 11, fontWeight: "500", textTransform: "uppercase", letterSpacing: 0 },
  statValue: { fontSize: 15, fontWeight: "700", marginTop: 4, fontVariant: ["tabular-nums"] },
  editStat: { position: "absolute", right: 10, top: 10 },
  searchBanner: { borderRadius: 14, borderWidth: 0, padding: 12, flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", gap: 8, marginBottom: 10 },
  searchBannerMobile: { marginHorizontal: 14 },
  tableCard: { borderWidth: 0, borderRadius: 14, overflow: "hidden", marginBottom: 18 },
  summaryTableMobile: { borderRadius: 14 },
  empty: { padding: 18, textAlign: "center", fontWeight: "500" },
  mobileEmptyCard: { borderWidth: 0, borderRadius: 14 },
  selectionBar: { marginHorizontal: 14, marginBottom: 10, borderWidth: 0, borderRadius: 14, padding: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  selectionText: { flex: 1, minWidth: 0, fontSize: 14, fontWeight: "600" },
  selectionActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  selectionBtn: { width: 42, height: 42, borderRadius: 10, borderWidth: 1, alignItems: "center", justifyContent: "center" },
  groupedList: { paddingHorizontal: 14, gap: 18 },
  dateGroup: { gap: 8 },
  dateGroupLabel: { paddingHorizontal: 4, fontSize: 11, fontWeight: "600", letterSpacing: 0 },
  txGroupCard: { borderWidth: 0, borderRadius: 14, overflow: "hidden" },
  groupedTxRow: { minHeight: 64, paddingHorizontal: 16, paddingVertical: 12, flexDirection: "row", alignItems: "center", gap: 12 },
  txIcon: { width: 40, height: 40, borderRadius: 20, borderWidth: 0, alignItems: "center", justifyContent: "center" },
  groupedTxMain: { flex: 1, minWidth: 0 },
  groupedTxTitle: { fontSize: 14, fontWeight: "600" },
  groupedTxMeta: { marginTop: 2, fontSize: 12, fontWeight: "400" },
  groupedTxAmount: { maxWidth: 116, fontSize: 14, fontWeight: "700", textAlign: "right", fontVariant: ["tabular-nums"] },
  sectionHeader: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 8 },
  sectionCardRow: { marginHorizontal: 14 },
  sectionCardFirstRow: { borderTopLeftRadius: 14, borderTopRightRadius: 14 },
  sectionCardLastRow: { borderBottomLeftRadius: 14, borderBottomRightRadius: 14 },
  loadOlderBtn: { minHeight: 48, borderWidth: 0, borderRadius: 14, alignItems: "center", justifyContent: "center", marginBottom: 12 },
  loadOlderText: { fontSize: 11, fontWeight: "600", letterSpacing: 0 },
  undoFab: { position: "absolute", left: 18, bottom: 112, zIndex: 28, borderRadius: 999, borderWidth: 0, paddingVertical: 12, paddingHorizontal: 16, flexDirection: "row", gap: 8 },
  bottomNav: { position: "absolute", left: 12, right: 12, bottom: 16, height: 68, zIndex: 24, overflow: "visible" },
  bottomNavGlass: { ...StyleSheet.absoluteFill, borderWidth: 0.5, borderRadius: 22, overflow: "hidden" },
  bottomNavContent: { height: "100%", paddingTop: 8, paddingBottom: 8, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", gap: 4, overflow: "visible" },
  bottomNavItem: { flex: 1, minWidth: 0, minHeight: 50, borderRadius: 14, alignItems: "center", justifyContent: "center", gap: 3 },
  bottomAddButton: { width: 56, height: 56, borderRadius: 17, alignItems: "center", justifyContent: "center", transform: [{ translateY: -16 }] },
  bottomNavLabel: { fontSize: 11, fontWeight: "500" },
  accountInitial: { fontSize: 24, fontWeight: "700" },
  accountHeroName: { fontSize: 18, fontWeight: "700" },
  accountHeroEmail: { fontSize: 13, fontWeight: "500", marginTop: 4 },
  kpiGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 12 },
  kpiGridMobile: { gap: 8, marginBottom: 10 },
  kpi: { flex: 1, minWidth: 0, borderWidth: 0, borderRadius: 14, padding: 14 },
  kpiValue: { fontSize: 22, fontWeight: "700", marginTop: 6, fontVariant: ["tabular-nums"] },
  chartRow: { flexDirection: "row", gap: 10, marginBottom: 12 },
  chartRowMobile: { flexDirection: "column", gap: 10 },
  chartCard: { flex: 1, borderWidth: 0, borderRadius: 14, padding: 14, alignItems: "center", marginBottom: 12 },
  chartCardMobile: { width: "100%" },
  sectionTitle: { alignSelf: "flex-start", fontSize: 16, fontWeight: "700", marginBottom: 12 },
  piePct: { position: "absolute", top: 82, fontSize: 18, fontWeight: "700" },
  summaryRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 16, paddingHorizontal: 14, borderBottomWidth: 0 },
  summaryMonth: { fontWeight: "600" },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.62)", justifyContent: "center", padding: 14 },
  modal: { borderRadius: 8, padding: 16, maxWidth: 620, maxHeight: "90%", width: "100%", alignSelf: "center" },
  recordModal: { borderWidth: 0, borderRadius: 20, width: "100%", maxWidth: 390, maxHeight: "90%", alignSelf: "center", overflow: "hidden" },
  recordHeader: { minHeight: 68, borderBottomWidth: 1, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  recordTitle: { flex: 1, minWidth: 0, fontSize: 19, fontWeight: "700" },
  closeBtn: { width: 42, height: 42, borderRadius: 12, borderWidth: 0, alignItems: "center", justifyContent: "center" },
  recordScroll: { flexShrink: 1, maxHeight: "100%" },
  recordBody: { padding: 16, paddingBottom: 20 },
  selectInput: { minHeight: 56, borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, marginBottom: 18 },
  selectTypeLeft: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 10 },
  typeDot: { width: 11, height: 11, borderRadius: 6 },
  selectTypeText: { flex: 1, minWidth: 0, fontSize: 16, fontWeight: "600" },
  moneyInputWrap: { height: 56, borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", marginBottom: 18 },
  moneyPrefix: { fontSize: 18, fontWeight: "700", marginRight: 14 },
  moneyInput: { flex: 1, height: "100%", fontSize: 18, fontWeight: "600", fontVariant: ["tabular-nums"] },
  moneyPreview: { maxWidth: 118, marginLeft: 10, fontSize: 13, fontWeight: "700", textAlign: "right", fontVariant: ["tabular-nums"] },
  calcToolbar: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: -10, marginBottom: 18 },
  calcChip: { minWidth: 38, height: 34, borderRadius: 10, alignItems: "center", justifyContent: "center", paddingHorizontal: 10 },
  calcChipText: { fontSize: 17, fontWeight: "700" },
  recordActions: { flexDirection: "row", gap: 10, marginTop: 8 },
  recordCancel: { flex: 1, height: 52, borderRadius: 12, borderWidth: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 },
  recordSubmit: { flex: 1, height: 52, borderRadius: 12, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 },
  recordCancelText: { fontSize: 15, fontWeight: "700" },
  recordSubmitText: { fontSize: 15, fontWeight: "700" },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 14 },
  modalTitle: { fontSize: 18, fontWeight: "700" },
  label: { fontSize: 12, fontWeight: "600", marginBottom: 6 },
  input: { borderWidth: 1, borderRadius: 10, paddingVertical: 11, paddingHorizontal: 12, fontWeight: "500" },
  inputIcon: { position: "absolute", right: 14, top: 12 },
  twoCols: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  modalActions: { flexDirection: "row", flexWrap: "wrap", justifyContent: "flex-end", gap: 10, marginTop: 8 },
  cancelBtn: { borderRadius: 8, paddingVertical: 12, paddingHorizontal: 14 },
  saveBtn: { borderRadius: 8, paddingVertical: 12, paddingHorizontal: 18 },
  saveText: { fontWeight: "700" },
  pagePanel: { borderWidth: 0, borderRadius: 14, padding: 16 },
  pagePanelHeader: { flexDirection: "row", alignItems: "center", gap: 9, marginBottom: 14 },
  pagePanelTitle: { fontSize: 18, fontWeight: "700" },
  settingsSection: { marginBottom: 22 },
  settingsLabel: { fontSize: 11, fontWeight: "600", marginBottom: 8, paddingHorizontal: 3, letterSpacing: 0 },
  settingsGroup: { borderWidth: 0, borderRadius: 14, overflow: "hidden" },
  settingsRow: { minHeight: 52, paddingHorizontal: 16, paddingVertical: 12, flexDirection: "row", alignItems: "center", gap: 12 },
  settingsAvatar: { width: 44, height: 44, borderRadius: 22, borderWidth: 0, alignItems: "center", justifyContent: "center" },
  settingsRowText: { flex: 1, minWidth: 0 },
  settingsRowLabel: { flex: 1, minWidth: 0, fontSize: 14, fontWeight: "600" },
  settingsRowValue: { maxWidth: 116, fontSize: 13, fontWeight: "600", textAlign: "right" },
  signOutBtn: { alignSelf: "center", paddingHorizontal: 18, paddingVertical: 14 },
  signOutText: { fontSize: 14, fontWeight: "700" },
  optionOverlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,0.58)" },
  optionBackdrop: { ...StyleSheet.absoluteFill },
  optionSheet: { width: "100%", maxHeight: "70%", borderTopWidth: 0, borderTopLeftRadius: 20, borderTopRightRadius: 20, overflow: "hidden" },
  optionHeader: { minHeight: 62, borderBottomWidth: 1, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  optionTitle: { flex: 1, minWidth: 0, fontSize: 19, fontWeight: "700" },
  optionClose: { width: 40, height: 40, borderRadius: 12, borderWidth: 0, alignItems: "center", justifyContent: "center" },
  optionList: { flexShrink: 1 },
  optionListContent: { padding: 14, gap: 8, paddingBottom: 22 },
  optionRow: { minHeight: 54, borderRadius: 12, borderWidth: 0, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 11 },
  optionIcon: { width: 32, height: 32, borderRadius: 16, borderWidth: 0, alignItems: "center", justifyContent: "center" },
  optionLabel: { flex: 1, minWidth: 0, fontSize: 15, fontWeight: "600" },
  searchOverlay: { flex: 1, justifyContent: "flex-end" },
  searchSheet: { width: "100%", maxHeight: "88%", borderTopWidth: 0, borderTopLeftRadius: 22, borderTopRightRadius: 22, overflow: "hidden" },
  searchGrabber: { width: 42, height: 4, borderRadius: 999, alignSelf: "center", marginTop: 9, marginBottom: 8 },
  searchHeader: { minHeight: 66, paddingHorizontal: 16, paddingBottom: 13, flexDirection: "row", alignItems: "center", gap: 12 },
  searchHeaderIcon: { width: 42, height: 42, borderRadius: 13, alignItems: "center", justifyContent: "center" },
  searchTitleBlock: { flex: 1, minWidth: 0 },
  searchTitle: { fontSize: 19, fontWeight: "700" },
  searchSubtitle: { marginTop: 3, fontSize: 12, fontWeight: "500" },
  searchBody: { flexShrink: 1 },
  searchScrollContent: { paddingHorizontal: 14, paddingTop: 2, paddingBottom: 12, gap: 10 },
  searchSection: { borderWidth: 0, borderRadius: 14, padding: 12, gap: 10 },
  searchSectionHeader: { flexDirection: "row", alignItems: "center", gap: 8 },
  searchSectionTitle: { fontSize: 13, fontWeight: "600", textTransform: "uppercase" },
  searchFieldGrid: { flexDirection: "row", gap: 10 },
  searchActions: { borderTopWidth: 1, paddingHorizontal: 14, paddingTop: 12, paddingBottom: 14, flexDirection: "row", gap: 10 },
  searchActionBtn: { flex: 1, minHeight: 52, borderWidth: 1, borderRadius: 14, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  searchActionPrimary: { borderWidth: 0 },
  searchActionText: { fontSize: 14, fontWeight: "700" },
  detailModal: { borderRadius: 20, borderWidth: 0, width: "100%", maxWidth: 390, maxHeight: "90%", alignSelf: "center", overflow: "hidden" },
  detailScroll: { flexShrink: 1 },
  detailBody: { gap: 12, padding: 16 },
  detailHero: { borderRadius: 14, padding: 14, flexDirection: "row", alignItems: "center", gap: 12 },
  detailHeroIcon: { width: 48, height: 48, borderRadius: 24, alignItems: "center", justifyContent: "center" },
  detailHeroText: { flex: 1, minWidth: 0 },
  detailHeroLabel: { fontSize: 11, fontWeight: "600", textTransform: "uppercase" },
  detailHeroAmount: { marginTop: 4, fontSize: 28, fontWeight: "700", fontVariant: ["tabular-nums"] },
  detailDescription: { borderRadius: 12, padding: 14, gap: 7 },
  detailSectionLabel: { fontSize: 12, fontWeight: "600", textTransform: "uppercase" },
  detailDescriptionText: { fontSize: 16, fontWeight: "500", lineHeight: 22 },
  detailMetaGrid: { flexDirection: "row", gap: 10 },
  detailMetaItem: { flex: 1, minWidth: 0, padding: 12, flexDirection: "row", alignItems: "center", gap: 9 },
  detailMetaText: { flex: 1, minWidth: 0 },
  detailMetaLabel: { fontSize: 11, fontWeight: "600", textTransform: "uppercase" },
  detailMetaValue: { marginTop: 3, fontSize: 13, fontWeight: "600" },
  exportChip: { flex: 1, minHeight: 48, borderWidth: 1, borderRadius: 10, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  gasTableHeader: { flexDirection: "row", borderBottomWidth: 0, paddingVertical: 10, paddingHorizontal: 8 },
  gasTableHeadCell: { flex: 1, fontSize: 10, fontWeight: "600", textAlign: "center" },
  gasTableRow: { flexDirection: "row", borderBottomWidth: 0.5, paddingVertical: 12, paddingHorizontal: 8 },
  gasTableCell: { flex: 1, fontSize: 11, fontWeight: "500", textAlign: "center", fontVariant: ["tabular-nums"] },
  detailActions: { flexDirection: "row", gap: 10 },
  detailActionBtn: { flex: 1, height: 48, borderRadius: 12, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  detailActionText: { fontSize: 14, fontWeight: "700" },
});
