import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  shell: { flex: 1, flexDirection: "row", padding: 12, gap: 12 },
  shellCompact: { flexDirection: "column", padding: 0, gap: 0 },
  content: { flex: 1 },
  pageScroll: { paddingBottom: 172 },
  pageScrollMobile: { paddingHorizontal: 14 },
  loginScreen: { flex: 1, alignItems: "center", justifyContent: "center", padding: 26 },
  loginMark: { width: 78, height: 78, borderRadius: 18, borderWidth: 1, alignItems: "center", justifyContent: "center", marginBottom: 18 },
  loginTitle: { fontSize: 30, fontWeight: "900", textAlign: "center" },
  googleLoginBtn: { minWidth: 232, minHeight: 50, marginTop: 22, borderRadius: 8, paddingVertical: 13, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10 },
  googleLoginText: { fontSize: 15, fontWeight: "900" },
  loginStatus: { marginTop: 14, fontSize: 12, fontWeight: "700", textAlign: "center" },
  topBar: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
  topBarMobile: { marginBottom: 0, paddingHorizontal: 12, paddingVertical: 10 },
  headerLeft: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 10 },
  headerLogo: { width: 40, height: 40, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  titleBlock: { flex: 1, minWidth: 0 },
  pageTitle: { fontSize: 28, fontWeight: "900" },
  pageTitleMobile: { fontSize: 20 },
  pageSub: { fontSize: 13, fontWeight: "700" },
  pageSubMobile: { fontSize: 14 },
  themeToggle: { width: 58, height: 34, borderRadius: 999, paddingHorizontal: 4, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  themeThumb: { width: 29, height: 29, borderRadius: 15, backgroundColor: "#ffffff" },
  periodControls: { paddingHorizontal: 14, paddingTop: 12, paddingBottom: 12, gap: 10 },
  periodTitleBlock: { gap: 3 },
  periodEyebrow: { fontSize: 10, fontWeight: "900", letterSpacing: 0 },
  periodTitle: { fontSize: 18, fontWeight: "900" },
  periodActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  periodSelect: { minHeight: 42, borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  periodMonthSelect: { flex: 1, minWidth: 0 },
  periodSelectText: { fontSize: 14, fontWeight: "900" },
  periodToday: { width: 42, height: 42, borderRadius: 10, borderWidth: 1, alignItems: "center", justifyContent: "center" },
  connectText: { fontSize: 12, fontWeight: "700", lineHeight: 18 },
  loadingBar: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 10 },
  skeletonScreen: { flex: 1, padding: 14, gap: 14 },
  skeletonHeader: { borderWidth: 1, borderRadius: 12, padding: 14, flexDirection: "row", alignItems: "center", gap: 12 },
  skeletonGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  skeletonCard: { width: "48.8%", borderWidth: 1, borderRadius: 12, padding: 12, flexDirection: "row", alignItems: "center", gap: 10 },
  skeletonTable: { flex: 1, borderWidth: 1, borderRadius: 18, padding: 12, gap: 10 },
  skeletonRow: { height: 42, borderRadius: 8 },
  skeletonBox: { borderRadius: 8, opacity: 0.92 },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 12 },
  statsGridMobile: { paddingHorizontal: 14, paddingTop: 12, paddingBottom: 10, gap: 8, marginBottom: 0 },
  statCard: { flexGrow: 1, flexBasis: "48%", minWidth: 0, borderWidth: 1, borderRadius: 11, padding: 12, position: "relative", flexDirection: "row", alignItems: "center", gap: 10 },
  statIcon: { width: 34, height: 34, borderRadius: 8, alignItems: "center", justifyContent: "center" },
  statContent: { flex: 1, minWidth: 0 },
  statLabel: { fontSize: 10, fontWeight: "900", textTransform: "uppercase" },
  statValue: { fontSize: 15, fontWeight: "900", marginTop: 4 },
  editStat: { position: "absolute", right: 10, top: 10 },
  searchBanner: { borderRadius: 8, borderWidth: 1, padding: 12, flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", gap: 8, marginBottom: 10 },
  searchBannerMobile: { marginHorizontal: 14 },
  tableCard: { borderWidth: 1, borderRadius: 8, overflow: "hidden", marginBottom: 18 },
  summaryTableMobile: { borderRadius: 14 },
  empty: { padding: 18, textAlign: "center", fontWeight: "700" },
  mobileEmptyCard: { borderWidth: 1, borderRadius: 14 },
  selectionBar: { marginHorizontal: 14, marginBottom: 10, borderWidth: 1, borderRadius: 12, padding: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  selectionText: { flex: 1, minWidth: 0, fontSize: 14, fontWeight: "900" },
  selectionActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  selectionBtn: { width: 42, height: 42, borderRadius: 10, borderWidth: 1, alignItems: "center", justifyContent: "center" },
  groupedList: { paddingHorizontal: 14, gap: 18 },
  dateGroup: { gap: 8 },
  dateGroupLabel: { paddingHorizontal: 4, fontSize: 11, fontWeight: "900", letterSpacing: 0 },
  txGroupCard: { borderWidth: 1, borderRadius: 8, overflow: "hidden" },
  groupedTxRow: { minHeight: 60, paddingHorizontal: 12, paddingVertical: 10, flexDirection: "row", alignItems: "center", gap: 11 },
  txIcon: { width: 38, height: 38, borderRadius: 19, borderWidth: 1, alignItems: "center", justifyContent: "center" },
  groupedTxMain: { flex: 1, minWidth: 0 },
  groupedTxTitle: { fontSize: 14, fontWeight: "900" },
  groupedTxMeta: { marginTop: 2, fontSize: 11, fontWeight: "800" },
  groupedTxAmount: { maxWidth: 110, fontSize: 14, fontWeight: "900", textAlign: "right" },
  loadOlderBtn: { minHeight: 48, borderWidth: 1, borderRadius: 8, alignItems: "center", justifyContent: "center", marginBottom: 12 },
  loadOlderText: { fontSize: 11, fontWeight: "900", letterSpacing: 0 },
  undoFab: { position: "absolute", left: 18, bottom: 96, borderRadius: 999, borderWidth: 1, paddingVertical: 12, paddingHorizontal: 16, flexDirection: "row", gap: 8 },
  bottomNav: { position: "absolute", left: 0, right: 0, bottom: 0, minHeight: 78, borderTopWidth: 1, paddingTop: 8, paddingBottom: 10, paddingHorizontal: 8, flexDirection: "row", alignItems: "center", gap: 4 },
  bottomNavItem: { flex: 1, minWidth: 0, minHeight: 56, borderRadius: 14, alignItems: "center", justifyContent: "center", gap: 4 },
  bottomAddButton: { width: 64, height: 64, borderRadius: 32, alignItems: "center", justifyContent: "center", marginTop: -24 },
  bottomNavLabel: { fontSize: 11, fontWeight: "900" },
  sheetChoice: { borderWidth: 1, borderRadius: 10, padding: 12, flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 10 },
  sheetChoiceTitle: { fontSize: 15, fontWeight: "900" },
  sheetChoiceMeta: { fontSize: 12, fontWeight: "700", marginTop: 3 },
  accountInitial: { fontSize: 24, fontWeight: "900" },
  accountHeroName: { fontSize: 18, fontWeight: "900" },
  accountHeroEmail: { fontSize: 13, fontWeight: "700", marginTop: 4 },
  kpiGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 12 },
  kpiGridMobile: { gap: 8, marginBottom: 10 },
  kpi: { flexGrow: 1, flexBasis: "23%", minWidth: 150, borderWidth: 1, borderRadius: 8, padding: 14 },
  kpiValue: { fontSize: 20, fontWeight: "900", marginTop: 5 },
  chartRow: { flexDirection: "row", gap: 10, marginBottom: 12 },
  chartRowMobile: { flexDirection: "column", gap: 10 },
  chartCard: { flex: 1, borderWidth: 1, borderRadius: 8, padding: 14, alignItems: "center", marginBottom: 12 },
  chartCardMobile: { width: "100%" },
  sectionTitle: { alignSelf: "flex-start", fontSize: 16, fontWeight: "900", marginBottom: 10 },
  piePct: { position: "absolute", top: 82, fontSize: 18, fontWeight: "900" },
  summaryRow: { flexDirection: "row", justifyContent: "space-between", padding: 14, borderBottomWidth: 1 },
  summaryMonth: { fontWeight: "900" },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.62)", justifyContent: "center", padding: 14 },
  modal: { borderRadius: 8, padding: 16, maxWidth: 620, maxHeight: "90%", width: "100%", alignSelf: "center" },
  recordModal: { borderWidth: 1, borderRadius: 20, width: "100%", maxWidth: 390, maxHeight: "90%", alignSelf: "center", overflow: "hidden" },
  recordHeader: { minHeight: 68, borderBottomWidth: 1, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  recordTitle: { flex: 1, minWidth: 0, fontSize: 19, fontWeight: "900" },
  closeBtn: { width: 42, height: 42, borderRadius: 12, borderWidth: 1, alignItems: "center", justifyContent: "center" },
  recordScroll: { flexShrink: 1, maxHeight: "100%" },
  recordBody: { padding: 18, paddingBottom: 20 },
  selectInput: { minHeight: 56, borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, marginBottom: 18 },
  selectTypeLeft: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 10 },
  typeDot: { width: 11, height: 11, borderRadius: 6 },
  selectTypeText: { flex: 1, minWidth: 0, fontSize: 16, fontWeight: "900" },
  moneyInputWrap: { height: 52, borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", marginBottom: 18 },
  moneyPrefix: { fontSize: 18, fontWeight: "900", marginRight: 14 },
  moneyInput: { flex: 1, height: "100%", fontSize: 16, fontWeight: "800" },
  recordActions: { flexDirection: "row", gap: 10, marginTop: 8 },
  recordCancel: { flex: 1, height: 52, borderRadius: 12, borderWidth: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 },
  recordSubmit: { flex: 1, height: 52, borderRadius: 12, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 },
  recordCancelText: { fontSize: 15, fontWeight: "900" },
  recordSubmitText: { fontSize: 15, fontWeight: "900" },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 14 },
  modalTitle: { fontSize: 18, fontWeight: "900" },
  label: { fontSize: 12, fontWeight: "900", marginBottom: 6 },
  input: { borderWidth: 1, borderRadius: 8, paddingVertical: 11, paddingHorizontal: 12, fontWeight: "800" },
  inputIcon: { position: "absolute", right: 14, top: 12 },
  twoCols: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  modalActions: { flexDirection: "row", flexWrap: "wrap", justifyContent: "flex-end", gap: 10, marginTop: 8 },
  cancelBtn: { borderRadius: 8, paddingVertical: 12, paddingHorizontal: 14 },
  saveBtn: { borderRadius: 8, paddingVertical: 12, paddingHorizontal: 18 },
  saveText: { fontWeight: "900" },
  pagePanel: { borderWidth: 1, borderRadius: 8, padding: 16 },
  pagePanelHeader: { flexDirection: "row", alignItems: "center", gap: 9, marginBottom: 14 },
  pagePanelTitle: { fontSize: 18, fontWeight: "900" },
  settingsSection: { marginBottom: 22 },
  settingsLabel: { fontSize: 11, fontWeight: "900", marginBottom: 8, paddingHorizontal: 3, letterSpacing: 0 },
  settingsGroup: { borderWidth: 1, borderRadius: 8, overflow: "hidden" },
  settingsRow: { minHeight: 52, paddingHorizontal: 13, paddingVertical: 11, flexDirection: "row", alignItems: "center", gap: 12 },
  settingsAvatar: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, alignItems: "center", justifyContent: "center" },
  settingsRowText: { flex: 1, minWidth: 0 },
  settingsRowLabel: { flex: 1, minWidth: 0, fontSize: 14, fontWeight: "900" },
  signOutBtn: { alignSelf: "center", paddingHorizontal: 18, paddingVertical: 14 },
  signOutText: { fontSize: 14, fontWeight: "900" },
  optionOverlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,0.58)" },
  optionBackdrop: { ...StyleSheet.absoluteFill },
  optionSheet: { width: "100%", maxHeight: "70%", borderTopWidth: 1, borderTopLeftRadius: 20, borderTopRightRadius: 20, overflow: "hidden" },
  optionHeader: { minHeight: 62, borderBottomWidth: 1, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  optionTitle: { flex: 1, minWidth: 0, fontSize: 19, fontWeight: "900" },
  optionClose: { width: 40, height: 40, borderRadius: 12, borderWidth: 1, alignItems: "center", justifyContent: "center" },
  optionList: { flexShrink: 1 },
  optionListContent: { padding: 14, gap: 8, paddingBottom: 22 },
  optionRow: { minHeight: 54, borderRadius: 12, borderWidth: 1, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 11 },
  optionIcon: { width: 34, height: 34, borderRadius: 17, borderWidth: 1, alignItems: "center", justifyContent: "center" },
  optionLabel: { flex: 1, minWidth: 0, fontSize: 15, fontWeight: "900" },
  detailModal: { borderRadius: 20, borderWidth: 1, width: "100%", maxWidth: 390, maxHeight: "90%", alignSelf: "center", overflow: "hidden" },
  detailScroll: { flexShrink: 1 },
  detailBody: { gap: 12, padding: 18 },
  detailHero: { borderRadius: 16, padding: 14, flexDirection: "row", alignItems: "center", gap: 12 },
  detailHeroIcon: { width: 48, height: 48, borderRadius: 24, alignItems: "center", justifyContent: "center" },
  detailHeroText: { flex: 1, minWidth: 0 },
  detailHeroLabel: { fontSize: 11, fontWeight: "900", textTransform: "uppercase" },
  detailHeroAmount: { marginTop: 4, fontSize: 24, fontWeight: "900" },
  detailDescription: { borderRadius: 14, padding: 14, gap: 7 },
  detailSectionLabel: { fontSize: 12, fontWeight: "900", textTransform: "uppercase" },
  detailDescriptionText: { fontSize: 16, fontWeight: "800", lineHeight: 22 },
  detailMetaGrid: { flexDirection: "row", gap: 10 },
  detailMetaItem: { flex: 1, minWidth: 0, borderRadius: 14, padding: 12, flexDirection: "row", alignItems: "center", gap: 9 },
  detailMetaText: { flex: 1, minWidth: 0 },
  detailMetaLabel: { fontSize: 11, fontWeight: "900", textTransform: "uppercase" },
  detailMetaValue: { marginTop: 3, fontSize: 13, fontWeight: "900" },
  exportChip: { flex: 1, minHeight: 48, borderWidth: 1, borderRadius: 10, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  gasTableHeader: { flexDirection: "row", borderBottomWidth: 1, paddingVertical: 10, paddingHorizontal: 8 },
  gasTableHeadCell: { flex: 1, fontSize: 10, fontWeight: "900", textAlign: "center" },
  gasTableRow: { flexDirection: "row", borderBottomWidth: 1, paddingVertical: 9, paddingHorizontal: 8 },
  gasTableCell: { flex: 1, fontSize: 11, fontWeight: "800", textAlign: "center" },
  detailActions: { flexDirection: "row", gap: 10 },
  detailActionBtn: { flex: 1, height: 48, borderRadius: 12, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  detailActionText: { fontSize: 14, fontWeight: "900" },
});
