import type { FontPreference, MaterialIconName } from "@/types";

export const FONT_FAMILIES: Record<FontPreference, string> = {
  dmsans: "DMSans",
  serif: "serif",
  mono: "monospace",
  condensed: "sans-serif-condensed",
  light: "sans-serif-light",
  casual: "casual",
  cursive: "cursive",
  smallcaps: "sans-serif-smallcaps",
  inter: "Inter",
  fredoka: "Fredoka",
  jetbrainsmono: "JetBrainsMono",
  spacemono: "SpaceMono",
  orbitron: "Orbitron",
  playfair: "PlayfairDisplay",
  bebasneue: "BebasNeue",
  comicneue: "ComicNeue",
  sora: "Sora",
  patrickhand: "PatrickHand",
  plusjakartasans: "PlusJakartaSans",
  intervariable: "InterVariable",
  comicsansms: "ComicSansMS",
  proggysquare: "ProggySquare",
  redstarbold: "RedstarBold",
  sansi: "SANSI",
  sfscribbledsans: "SFScribbledSans",
};

export const FONT_SIZE_SCALE: Partial<Record<FontPreference, number>> = {
  sansi: 1.35,
  sfscribbledsans: 1.3,
  proggysquare: 1.4,
  comicsansms: 1.2,
};

export const FONT_ICONS: Record<FontPreference, MaterialIconName> = {
  dmsans: "format-font",
  serif: "format-letter-case",
  mono: "code-tags",
  condensed: "format-letter-spacing",
  light: "feather",
  casual: "draw",
  cursive: "fountain-pen-tip",
  smallcaps: "format-letter-case-upper",
  inter: "format-font",
  intervariable: "format-font",
  jetbrainsmono: "code-tags",
  spacemono: "code-tags",
  orbitron: "rocket-launch",
  playfair: "format-letter-case",
  bebasneue: "format-letter-spacing",
  fredoka: "balloon",
  comicneue: "emoticon-happy",
  patrickhand: "draw",
  sora: "format-font",
  plusjakartasans: "format-font",
  comicsansms: "emoticon-happy",
  proggysquare: "code-tags",
  redstarbold: "star",
  sansi: "format-font",
  sfscribbledsans: "draw",
};
